# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!([
  {username: "aang", password_digest: "$2a$12$Pp6A6IZIvSX0piPcgN/inuvB2VZHJkjQ.iucDEXZa9oLbah060CbS", bio: "literally the last airbender", avatar: "thelastairbender"},
  {username: "aang2", password_digest: "$2a$12$no.4/5/5M/Ri56KAl.j9be4aidy3MU7p4Bdt6lpE71dzcbw4XNtI.", bio: "literally the last airbender", avatar: "thelastairbender"},
  {username: "aang3", password_digest: "$2a$12$IHVmGJUMnzVSM51ubEEEKeU3oaojyFv1rKCYGf5qwnAsfaUAGCtCq", bio: "literally the last airbender", avatar: "thelastairbender"},
  {username: "aang4", password_digest: "$2a$12$38EJsKnVjsLUKCfMTNwTEulnk0bfuJGGVcnWnvrOmPaHU4OeBYVa2", bio: "literally the last airbender", avatar: "thelastairbender"},
  {username: "aaang", password_digest: "$2a$12$Q7CTAJmodugOflKrZS2/zeB/JP733EOO9HXI5RV7n3zULmV7RUCQ6", bio: "the", avatar: "thelastairbender"},
  {username: "rangi", password_digest: "$2a$12$rejuuq86jcTI6/S4BdFbwO4X7iOYuk59UYN31NV3FMlCMIlCyQxFS", bio: "firebender", avatar: "aFace"},
  {username: "Kyoshi", password_digest: "$2a$12$tlbY.djsLfl7DimV.cL1/.qoB16k.AhcEKbPticOqEcJi3qbuWCWu", bio: "avatar", avatar: "me"},
  {username: "hat", password_digest: "$2a$12$XxyM3Ab1g4IMVt4LQX0EvOg5IV5EYBvddlrePuJvamOpZ3eiJacO6", bio: "hat", avatar: "hat"},
  {username: "Sasuke", password_digest: "$2a$12$tauw8XoocCKt.jiAZcFckeEXf1mgpMMkOlen8WjxDyWRI/T32erA6", bio: "youre annoying", avatar: "no"},
  {username: "sakura", password_digest: "$2a$12$IhnqlvLTgSUkNaDmfE3kGeabFpj74AHgkYnGJvfV.m6HE2pk5IjYu", bio: "bio", avatar: "s"},
  {username: "kakashi", password_digest: "$2a$12$Tmr38/V70pzwMw0it6moPupSRLfnCJKfsYlcXSvk.THQNdTDUMOnG", bio: "life", avatar: "k"},
  {username: "Matthew", password_digest: "$2a$12$9kjFvtHfEa4VbyYyBH.jc.i.362YdBv978jVb2wiPDey0bBsnhHui", bio: "a programmer", avatar: "a pic"},
  {username: "mrmilton", password_digest: "$2a$12$1lPVmZRZY9rjerUE0a4Kj.vRV8UNsjXYkC9XgWFwIsvnXS0W24EqW", bio: "old teacher", avatar: "a pic"},
  {username: "Mr Milton", password_digest: "$2a$12$b2.V7LcmuiBnftN6bmA.6e6IFL.2sst4QZxQ.Xmy9JOBbFVn948dm", bio: "DRAMA TEACHER", avatar: "a picture"},
  {username: "2", password_digest: "$2a$12$nTQ5M6lO4l.WUSzTfwFIneB.loWqwbOzft3sWr2NFssY7RtC22gYq", bio: "2", avatar: "2"},
  {username: "3", password_digest: "$2a$12$.kwvhL1o1Ybt/84OJ29buedquIYfBGha68xTuk/o17WFIGufKVyWO", bio: "3", avatar: "3"},
  {username: "Cedric", password_digest: "$2a$12$MOgaXsK6Cc1W5BlrEIjuCOY59IQ9BSBBCKLfnn/RuSLvV/t.CM4/i", bio: "the man the myth the legend", avatar: "luna"},
  {username: "Naruto", password_digest: "$2a$12$FGABi4ZCVAVQSdO44adiGeJhviaDGtBxDHKCtcsdqGxZVMR.LcL/O", bio: "still a chunin", avatar: "a pic"},
  {username: "Matt", password_digest: "$2a$12$GBrb42nU2LfgerM2HGQiBeUb9oWBo3qhKlY9UncGXk/6JG7ZIfOlm", bio: "Matts Bio", avatar: "a pic"},
  {username: "nehemiah", password_digest: "$2a$12$PCvnyhcy7nV55kmCFTO.Uujy60F/hF5yRvmVhcEm5zcKwXQ/u1WcK", bio: "bio", avatar: "avatar"},
  {username: "MrMilton57", password_digest: "$2a$12$ZwY2TeRNMTzecvVk0HEMYuAsRGAZfPsQ7lPw44GG5kSE4vfYXuhjO", bio: "a teacher", avatar: "my avatar"},
  {username: "Mr Babbitt", password_digest: "$2a$12$ITxgsN8D/TKC8O08YNGTT.hc23LWe23pLdGYiUyJjLSFiNUOk80fy", bio: "", avatar: ""},
  {username: "Mr Harper", password_digest: "$2a$12$PDV25fmAl0FaIxus.DIxDujUwDCjdPKONqMWVjhDnvoDm7tR2SqMu", bio: "", avatar: ""},
  {username: "mike", password_digest: "$2a$12$oGd2Ev8xHMXAe1brpg8O1.oRjmJzAEDQpMeaq3CSD2FiwvS5TvyBW", bio: "", avatar: ""},
  {username: "matt57", password_digest: "$2a$12$l8UuQRiDEvMg9IRS8PFQ0OUfpVcircrFcjnxHsz1uhxt04bPsnyrm", bio: "", avatar: ""},
  {username: "sample", password_digest: "$2a$12$JaV4jmwYl7ttQ6MkZXWwAuQr4y1xFig4qlAE/FUb8TevTYehZT2XW", bio: "", avatar: ""},
  {username: "test13", password_digest: "$2a$12$XyC75pLhKvvms6hc3aTOLO77ElM5V9Y6pCPaIAS1G4ichAT0Gpg4u", bio: "", avatar: ""},
  {username: "4", password_digest: "$2a$12$bI6YrD6yUO8igZj8mwWm0eY5QjklptyQqq3.zM.A.TyJXz7u6.Qy2", bio: "", avatar: ""},
  {username: "9", password_digest: "$2a$12$6k4AK0yBAec30besRSs5ve1/8yFSofl.yGD/2ADfbEQt8ty5mobXy", bio: "", avatar: ""},
  {username: "8", password_digest: "$2a$12$pAaN4Z6zmAiUNaS9xlQxpuoXBpJmR0RO42Y/wKpblCA5MUdP1wNAa", bio: "", avatar: ""},
  {username: "7", password_digest: "$2a$12$Zt4iWZKhNq86WfzBD9Nl5O92J.PxomxkpQAdS9bu.88s0nabEG5ZO", bio: "", avatar: ""},
  {username: "6", password_digest: "$2a$12$fbzbcwsUUxmAK/VjRO1/NeGvHowCIm7Zr1X/cQK3Qa1LaeE8yR9Qq", bio: "", avatar: ""},
  {username: "5", password_digest: "$2a$12$30oUO2uDmaMvJK7dUaBHMuKxSBscRbTb0T6VFO0ZDvGVRp2QWZIw2", bio: "", avatar: ""},
  {username: "11", password_digest: "$2a$12$JYYT0Sds0XLBpiVx7SIR5e/OJJ4QUesS8BDgAkQ6HGat4R/3SxjT6", bio: "", avatar: ""},
  {username: "1", password_digest: "$2a$12$HclXAGTlXZPBxtNGt7HXre.kE333K0RNwd5gCeBeaVuVYXAH4fU62", bio: "1", avatar: "1"},
  {username: "delete me", password_digest: "$2a$12$c/jYVEYA8.8t0t8Xoi4Mi.dQ1pbrUoif8ucZMnPmKO6lufRtlY.v2", bio: "", avatar: ""},
  {username: "test", password_digest: "$2a$12$isZchPft/EcQDCfE81CBw.B09fGOeEgnDh3I5Z.mom0bBcCkfgwSi", bio: "", avatar: ""},
  {username: "deleteme", password_digest: "$2a$12$rMkZaeiMAmlm1Eon/lgnmeVSnG..DpdicT81i0E0lDKAxc2Vl9eCe", bio: "", avatar: ""}
])

Student.create!([
  {name: "Asami", user_id: 5},
  {name: "kam chancellor", user_id: 5},
  {name: "Marshawn Lynch", user_id: 5},
  {name: "asdsad", user_id: 27},
  {name: "Naga", user_id: 5},
  {name: "sdfdsf", user_id: 27},
  {name: "sdfasf", user_id: 27},
  {name: "wgwgwag", user_id: 27},
  {name: "Mike Jones", user_id: 5},
  {name: "matt", user_id: 5},
  {name: "Kitara", user_id: 5},
  {name: "Sakka", user_id: 5},
  {name: "Toph", user_id: 5},
  {name: "Suki", user_id: 5},
  {name: "Momo", user_id: 5},
  {name: "Zuko", user_id: 5},
  {name: "Iroh", user_id: 5},
  {name: "Korra", user_id: 5},
  {name: "Bolin", user_id: 5},
  {name: "Harry Potter", user_id: 5},
  {name: "Ron Weasley", user_id: 5},
  {name: "Hermionie Granger", user_id: 5},
  {name: "Luna Lovegood", user_id: 5},
  {name: "Luke Skywalker", user_id: 5},
  {name: "Han Solo", user_id: 5},
  {name: "Chewy", user_id: 5},
  {name: "R2-D2", user_id: 5},
  {name: "C3P0", user_id: 5},
  {name: "Naruto", user_id: 5},
  {name: "Josepheus", user_id: 5},
  {name: "Nehemiah", user_id: 5},
  {name: "Luxo", user_id: 5},
  {name: "Dale Jr.", user_id: 5},
  {name: "Dale Sr.", user_id: 5},
  {name: "Luna Lovedog", user_id: 5},
  {name: "Russell Wilson", user_id: 5},
  {name: "Bobby Wagner", user_id: 5},
  {name: "Bruce Irvin", user_id: 5},
  {name: "Steve Rogers", user_id: 5},
  {name: "Matt Murdock", user_id: 5},
  {name: "Luke Cage", user_id: 5},
  {name: "Cabbage Man", user_id: 5},
  {name: "Sherlock", user_id: 5},
  {name: "Starbuck", user_id: 5},
  {name: "Tupac", user_id: 5},
  {name: "The Duke", user_id: 5},
  {name: "Jet", user_id: 5},
  {name: "Biggie Smalls", user_id: 5},
  {name: "Bruce Wayne", user_id: 5},
  {name: "Clark Kent", user_id: 5},
  {name: "Mr Peanut", user_id: 5},
  {name: "Randy Johnson", user_id: 5},
  {name: "Joey Cora", user_id: 5},
  {name: "Duane Brown", user_id: 5},
  {name: "Nehemiah Milton", user_id: 5},
  {name: "Jamal Adams", user_id: 5},
  {name: "Kakashi Hatake", user_id: 5},
  {name: "Sasuke Uchiha", user_id: 5},
  {name: "Sakura Harano", user_id: 5},
  {name: "Shikamaru Nara", user_id: 5},
  {name: "Alan Parsons", user_id: 5},
  {name: "Kevin Flynn", user_id: 5},
  {name: "Bubba Walace", user_id: 5},
  {name: "Charles Xavier", user_id: 5},
  {name: "Logan Howlett", user_id: 5},
  {name: "Alan Kulwicki", user_id: 5},
  {name: "Benny Parsons", user_id: 5},
  {name: "Alvin Chipmunk", user_id: 5},
  {name: "James T Kirk", user_id: 5},
  {name: "Rusty Wallace", user_id: 5},
  {name: "the last airbender", user_id: 5},
  {name: "Firelord Azula", user_id: 5},
  {name: "Green Lantern", user_id: 5},
  {name: "cedric  m. doggery", user_id: 5},
  {name: "charlie bucket", user_id: 5},
  {name: "aaaaa", user_id: 16},
  {name: "aaa", user_id: 5},
  {name: "bob", user_id: 26},
  {name: "wergqergqreg", user_id: 27},
  {name: "bbb", user_id: 27},
  {name: "Sally Creamcheese", user_id: 28},
  {name: "Bob bobby", user_id: 28},
  {name: "Susie Creamcheese", user_id: 28},
  {name: "Billy Bob", user_id: 28},
  {name: "Tommy Tucker", user_id: 28},
  {name: "bob dole", user_id: 5}
])
ClassPeriod.create!([
  {subject: "new class", period: "6", level: 0, user_id: 5, max: 22},
  {subject: "Drama 1", period: "1", level: 0, user_id: 26, max: 31},
  {subject: "drama 2", period: "2", level: 0, user_id: 26, max: 10},
  {subject: "algebra", period: "1", level: 0, user_id: 27, max: 31},
  {subject: "freshmen math", period: "2", level: 0, user_id: 27, max: 31},
  {subject: "asdfasdfasdfdsf", period: "4", level: 0, user_id: 27, max: 4},
  {subject: "dfsafasdfasdffddddddddddddddd", period: "4", level: 0, user_id: 27, max: 4},
  {subject: "math", period: "1st", level: 0, user_id: 28, max: 31},
  {subject: "english", period: "2nd", level: 0, user_id: 28, max: 31},
  {subject: "Science", period: "3rd", level: 0, user_id: 28, max: 10},
  {subject: "Drama 2", period: "3", level: 0, user_id: 20, max: 30},
  {subject: "Drama 1", period: "5", level: 0, user_id: 20, max: 30},
  {subject: "Improv", period: "6", level: 0, user_id: 20, max: 30},
  {subject: "aangClass", period: "1", level: 1, user_id: 1, max: 30},
  {subject: "classwithuser", period: "1", level: 1, user_id: 1, max: 30},
  {subject: "earthbending", period: "1", level: 2, user_id: 8, max: 30},
  {subject: "firebending", period: "2", level: 0, user_id: 8, max: 30},
  {subject: "waterbending", period: "3", level: 0, user_id: 8, max: 30},
  {subject: "airbending", period: "4", level: 0, user_id: 8, max: 30},
  {subject: "CSS for newbs", period: "1-10", level: -50, user_id: 13, max: 30},
  {subject: "CSS for newbs", period: "1-10", level: -50, user_id: 13, max: 30},
  {subject: "Firebending 101", period: "0", level: 1, user_id: 7, max: 30},
  {subject: "Firebending", period: "2", level: 2, user_id: 7, max: 30},
  {subject: "Firebending", period: "3", level: 3, user_id: 7, max: 30},
  {subject: "AirBending for Beginners", period: "2", level: 5, user_id: 5, max: 30},
  {subject: "Drama", period: "1", level: 1, user_id: 14, max: 30},
  {subject: "Comedy Improv", period: "2", level: 1, user_id: 14, max: 30},
  {subject: "Drama", period: "3", level: 2, user_id: 14, max: 30},
  {subject: "Stage Tech", period: "5", level: 1, user_id: 14, max: 30},
  {subject: "Drama", period: "6", level: 1, user_id: 14, max: 30},
  {subject: "Drama 1", period: "1", level: 0, user_id: 20, max: 30},
  {subject: "Stagecraft", period: "2", level: 0, user_id: 20, max: 30},
  {subject: "Math 1", period: "1", level: 0, user_id: 21, max: 30},
  {subject: "Statistics", period: "2", level: 0, user_id: 21, max: 30},
  {subject: "Geometry", period: "3", level: 0, user_id: 21, max: 30},
  {subject: "Trig", period: "4", level: 0, user_id: 21, max: 30},
  {subject: "Math 2", period: "6", level: 0, user_id: 21, max: 30},
  {subject: "Drama 1", period: "1", level: 0, user_id: 22, max: 30},
  {subject: "StageCraft", period: "2", level: 0, user_id: 22, max: 30},
  {subject: "StageCraft", period: "2", level: 0, user_id: 22, max: 30},
  {subject: "Drama 2", period: "3", level: 0, user_id: 22, max: 30},
  {subject: "Film Studies", period: "5", level: 0, user_id: 22, max: 30},
  {subject: "Drama 1", period: "6", level: 0, user_id: 22, max: 30},
  {subject: "Production", period: "7", level: 0, user_id: 22, max: 30},
  {subject: "Racket sports", period: "4", level: 0, user_id: 5, max: 30},
  {subject: "English 2", period: "3", level: 0, user_id: 5, max: 30},
  {subject: "HTML and you", period: "5", level: 0, user_id: 5, max: 30},
  {subject: "small engines", period: "1", level: 0, user_id: 24, max: 30},
  {subject: "science 1", period: "1", level: 0, user_id: 25, max: 30},
  {subject: "Science 2", period: "2", level: 0, user_id: 25, max: 30},
  {subject: "3", period: "3", level: 0, user_id: 16, max: 30},
  {subject: "9th grade math", period: "1", level: 2000, user_id: 5, max: 30},
  {subject: "sdfasf", period: "", level: 0, user_id: 49, max: nil},
  {subject: "1", period: "1", level: 0, user_id: 50, max: 1}
])
Assessment.create!([
  {participating: true, comment: "", class_period_id: 25, student_id: 73, user_id: 5}
])
Registration.create!([
  {class_period_id: 25, student_id: 73, user_id: 5}
])
